//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongRequestManagerV2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SongRequestManagerV2.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   BLACK LIST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_BLACK_LIST {
            get {
                return ResourceManager.GetString("BUTTON_BLACK_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HISTORY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_HISTORY {
            get {
                return ResourceManager.GetString("BUTTON_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLAY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_PLAY {
            get {
                return ResourceManager.GetString("BUTTON_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Queue close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_QUEUE_CLOSE {
            get {
                return ResourceManager.GetString("BUTTON_QUEUE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Queue open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_QUEUE_OPEN {
            get {
                return ResourceManager.GetString("BUTTON_QUEUE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REPLAY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_REPLAY {
            get {
                return ResourceManager.GetString("BUTTON_REPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REQUESTS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_REQUESTS {
            get {
                return ResourceManager.GetString("BUTTON_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKIP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_SKIP {
            get {
                return ResourceManager.GetString("BUTTON_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View the history of song requests from the current session. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HOVERHINT_HISTORY {
            get {
                return ResourceManager.GetString("HOVERHINT_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go back to your current song request queue. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HOVERHINT_REQUESTS {
            get {
                return ResourceManager.GetString("HOVERHINT_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Progress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TEXT_DOWNLOAD_PROGRESS {
            get {
                return ResourceManager.GetString("TEXT_DOWNLOAD_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Song Request History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TEXT_FLOWCORDINATER_TITLE_HISTORY {
            get {
                return ResourceManager.GetString("TEXT_FLOWCORDINATER_TITLE_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Song Request Queue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TEXT_FLOWCORDINATER_TITLE_QUEUE {
            get {
                return ResourceManager.GetString("TEXT_FLOWCORDINATER_TITLE_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PerformanceMode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TEXT_PEFORMANCE_MODE {
            get {
                return ResourceManager.GetString("TEXT_PEFORMANCE_MODE", resourceCulture);
            }
        }
    }
}
